!Current Configuration:
!
!System Description "EdgeSwitch 48 500W, 1.9.2, Linux 3.6.5-03329b4a, 1.1.0.5102011"
!System Software Version "1.9.2"
!System Up Time          "3 days 16 hrs 17 mins 55 secs"
!Additional Packages     QOS,IPv6 Management,Routing
!Current SNTP Synchronized Time: Sep  5 17:37:58 2026 UTC
!
vlan database
vlan 10,20
exit

configure
line console
serial baudrate 9600
exit

line telnet
exit

line ssh
exit

!
exit